# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Lr4qiJxSPhuzwnMnDpUhRhFwCeP_2EJ
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread("i.webp")
cv2_imshow(rasm)

qora= cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)

from google.colab.patches import cv2_imshow
import cv2
rasm2= cv2.imread("rasm.webp")
cv2_imshow(rasm2)

qora= cv2.cvtColor(rasm2,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)

from google.colab.patches import cv2_imshow
import cv2
rasm3= cv2.imread("rasmlar.webp")
cv2_imshow(rasm3)

qora= cv2.cvtColor(rasm3,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)

from google.colab.patches import cv2_imshow
import cv2
rasm4= cv2.imread("rasmlara.webp")
cv2_imshow(rasm4)

qora= cv2.cvtColor(rasm4,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)

from google.colab.patches import cv2_imshow
import cv2
rasm5= cv2.imread("muhammad.webp")
cv2_imshow(rasm5)

qora= cv2.cvtColor(rasm5,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)